version : '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: aba_postgres
    environment:
      POSTGRES_USER: aba_user
      POSTGRES_PASSWORD: aba_password
      POSTGRES_DB: aba_db
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: